title: ðŸ¤– Muhammad Nouman Ahsan â€” Intelligent Systems Engineer
description: A curated collection of my work in machine learning and AI â€” showcasing ideas, experiments, and practical applications.

remote_theme: pages-themes/cayman@v0.2.0
show_downloads: false
google_analytics:
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
